//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DearManager {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DearManager.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DearManager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Friends과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupFriendAddButton {
            get {
                return ResourceManager.GetString("txtAddGroupFriendAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends of Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupFriendTitle {
            get {
                return ResourceManager.GetString("txtAddGroupFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupName {
            get {
                return ResourceManager.GetString("txtAddGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupNameSample {
            get {
                return ResourceManager.GetString("txtAddGroupNameSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting Group Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupNameTitle {
            get {
                return ResourceManager.GetString("txtAddGroupNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptAmountLabel {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptAmountPlaceholder {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptAmountTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptAmountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptMember {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptMemberAddButton {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptMemberAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dutch Treat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptMemberDutchButton {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptMemberDutchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is blank form(s). Please check once again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMBlankCaption {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMBlankCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is blank money form(s). Please check once again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMBlankMoneyCaption {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMBlankMoneyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found Blank Money과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMBlankMoneyTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMBlankMoneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found Blank과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMBlankTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMBlankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t divide by 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMDividedZeroCaption {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMDividedZeroCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Divided by 0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMDividedZeroTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMDividedZeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Money과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMMoneyPlaceholder {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMMoneyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sum of member&apos;s money is not same with the whole money. Is it OK?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMPriceErrorCaption {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMPriceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Money Equality Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptPageVMPriceErrorTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptPageVMPriceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of Receipt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptTagLabel {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Receipt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptTagPlaceholder {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptTagPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Receipt Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupReceiptTagTitle {
            get {
                return ResourceManager.GetString("txtAddGroupReceiptTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAddGroupTitle {
            get {
                return ResourceManager.GetString("txtAddGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtButtonCancel {
            get {
                return ResourceManager.GetString("txtButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtButtonNo {
            get {
                return ResourceManager.GetString("txtButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtButtonOK {
            get {
                return ResourceManager.GetString("txtButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtButtonYes {
            get {
                return ResourceManager.GetString("txtButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtCustomFriendRequestCommit {
            get {
                return ResourceManager.GetString("txtCustomFriendRequestCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deny과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtCustomFriendRequestReject {
            get {
                return ResourceManager.GetString("txtCustomFriendRequestReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Friend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtFriendsPageAddButton {
            get {
                return ResourceManager.GetString("txtFriendsPageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friend Request (Wait: 0)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtFriendsPageRequestCheck {
            get {
                return ResourceManager.GetString("txtFriendsPageRequestCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtFriendsPageRequestCheckAfter {
            get {
                return ResourceManager.GetString("txtFriendsPageRequestCheckAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friend Request (Wait: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtFriendsPageRequestCheckBefore {
            get {
                return ResourceManager.GetString("txtFriendsPageRequestCheckBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtFriendsPageTitle {
            get {
                return ResourceManager.GetString("txtFriendsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Members과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageMember {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///    See More과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageMore {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receipts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageReceipt {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Receipt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageTitleAddButton {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageTitleAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not the administrator(s) of this group.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageVMAdminCaption {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageVMAdminCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authority Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupReceiptPageVMAdminTitle {
            get {
                return ResourceManager.GetString("txtGroupReceiptPageVMAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupsPageAddButton {
            get {
                return ResourceManager.GetString("txtGroupsPageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Groups과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtGroupsPageTitle {
            get {
                return ResourceManager.GetString("txtGroupsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For using application, Please input your name and nickname.
        ///
        ///Your Nickname can&apos;t be duplicated.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageCaption {
            get {
                return ResourceManager.GetString("txtInputUserPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageNameLabel {
            get {
                return ResourceManager.GetString("txtInputUserPageNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input your name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageNamePlaceholder {
            get {
                return ResourceManager.GetString("txtInputUserPageNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname (Everyone can see)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageNicknameLabel {
            get {
                return ResourceManager.GetString("txtInputUserPageNicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input your nickname과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageNicknamePlaceholder {
            get {
                return ResourceManager.GetString("txtInputUserPageNicknamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageOKButton {
            get {
                return ResourceManager.GetString("txtInputUserPageOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thanks for using &apos;DearManager&apos;!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserPageTitle {
            get {
                return ResourceManager.GetString("txtInputUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are some blanks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserVMBlankCaption {
            get {
                return ResourceManager.GetString("txtInputUserVMBlankCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blanks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserVMBlankTitle {
            get {
                return ResourceManager.GetString("txtInputUserVMBlankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is duplicated nickname.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserVMDuplicatedCaption {
            get {
                return ResourceManager.GetString("txtInputUserVMDuplicatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicated Nickname과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtInputUserVMDuplicatedTitle {
            get {
                return ResourceManager.GetString("txtInputUserVMDuplicatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtMainFriends {
            get {
                return ResourceManager.GetString("txtMainFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Groups과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtMainGroup {
            get {
                return ResourceManager.GetString("txtMainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtMainProfile {
            get {
                return ResourceManager.GetString("txtMainProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageDialogCancel {
            get {
                return ResourceManager.GetString("txtProfilePageDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageDialogChangePhoto {
            get {
                return ResourceManager.GetString("txtProfilePageDialogChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageDialogRemovePhoto {
            get {
                return ResourceManager.GetString("txtProfilePageDialogRemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Big Photo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageDialogShowBigPhoto {
            get {
                return ResourceManager.GetString("txtProfilePageDialogShowBigPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Photo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageDialogTitle {
            get {
                return ResourceManager.GetString("txtProfilePageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Friends과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageFriendRemoveButton {
            get {
                return ResourceManager.GetString("txtProfilePageFriendRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;s Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePageProfileTitleUnit {
            get {
                return ResourceManager.GetString("txtProfilePageProfileTitleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Photo (Big)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfilePicturePageTitle {
            get {
                return ResourceManager.GetString("txtProfilePicturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete friend?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfileVMDialogCaption {
            get {
                return ResourceManager.GetString("txtProfileVMDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfileVMDialogNoButton {
            get {
                return ResourceManager.GetString("txtProfileVMDialogNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Remove Friend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfileVMDialogTitle {
            get {
                return ResourceManager.GetString("txtProfileVMDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtProfileVMDialogYesButton {
            get {
                return ResourceManager.GetString("txtProfileVMDialogYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageAllRepaymentLabel {
            get {
                return ResourceManager.GetString("txtRepaymentPageAllRepaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Money of All Repayment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageAllRepaymentPlaceholder {
            get {
                return ResourceManager.GetString("txtRepaymentPageAllRepaymentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageCancelButton {
            get {
                return ResourceManager.GetString("txtRepaymentPageCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repayment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageOKButton {
            get {
                return ResourceManager.GetString("txtRepaymentPageOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partitial:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPagePartRepaymentLabel {
            get {
                return ResourceManager.GetString("txtRepaymentPagePartRepaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Money of Partitial Repayment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPagePartRepaymentPlaceholder {
            get {
                return ResourceManager.GetString("txtRepaymentPagePartRepaymentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Will you change balance of {0}?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageQuestion {
            get {
                return ResourceManager.GetString("txtRepaymentPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is a repaid money.
        ///Is it right?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMConfirmCaption {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Repayment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMConfirmTitle {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Money label is blank.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMNoMoneyCaption {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMNoMoneyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank Money과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMNoMoneyTitle {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMNoMoneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Written money is more bigger than the balance. Is it OK?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMOverCaption {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMOverCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMOverTitle {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repayment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtRepaymentPageVMRepaymentText {
            get {
                return ResourceManager.GetString("txtRepaymentPageVMRepaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input ID of friend.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendPageCaptionLabel {
            get {
                return ResourceManager.GetString("txtSearchFriendPageCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendPageIDLabel {
            get {
                return ResourceManager.GetString("txtSearchFriendPageIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Input Your ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendPageIDPlaceholder {
            get {
                return ResourceManager.GetString("txtSearchFriendPageIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Friend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendPageLabel {
            get {
                return ResourceManager.GetString("txtSearchFriendPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You already have this friend on your friends list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMAlreadyCaption {
            get {
                return ResourceManager.GetString("txtSearchFriendVMAlreadyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is your friend&apos;s name 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMCheckCaption1 {
            get {
                return ResourceManager.GetString("txtSearchFriendVMCheckCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    right?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMCheckCaption2 {
            get {
                return ResourceManager.GetString("txtSearchFriendVMCheckCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Friend Request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMCheckTitle {
            get {
                return ResourceManager.GetString("txtSearchFriendVMCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail To Add Friend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMErrorTitle {
            get {
                return ResourceManager.GetString("txtSearchFriendVMErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is made up with numbers. Please check once again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMInputCaption {
            get {
                return ResourceManager.GetString("txtSearchFriendVMInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMInputTitle {
            get {
                return ResourceManager.GetString("txtSearchFriendVMInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t add you in your friends even you are so lonely. (HAHA JK)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMMeCaption {
            get {
                return ResourceManager.GetString("txtSearchFriendVMMeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friend request is succeed. Please wait to confirm your friend.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMSuccessCaption {
            get {
                return ResourceManager.GetString("txtSearchFriendVMSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success Request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMSuccessTitle {
            get {
                return ResourceManager.GetString("txtSearchFriendVMSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no such ID.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtSearchFriendVMWrongCaption {
            get {
                return ResourceManager.GetString("txtSearchFriendVMWrongCaption", resourceCulture);
            }
        }
    }
}
